# Generated by Django 3.0.5 on 2020-04-15 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statemodel',
            fields=[
                ('state_no', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Citymodel',
            fields=[
                ('City_no', models.AutoField(primary_key=True, serialize=False)),
                ('City_name', models.CharField(max_length=40, unique=True)),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.Statemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Areamodel',
            fields=[
                ('Area_no', models.AutoField(primary_key=True, serialize=False)),
                ('Area_name', models.CharField(max_length=40, unique=True)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.Citymodel')),
            ],
        ),
    ]
