# Generated by Django 3.0.5 on 2020-04-17 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('s_admin', '0003_restautanttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantModel',
            fields=[
                ('rest_id', models.AutoField(primary_key=True, serialize=False)),
                ('rest_name', models.CharField(max_length=40, unique=True)),
                ('rest_contact', models.IntegerField(unique=True)),
                ('rest_Email', models.EmailField(max_length=50, unique=True)),
                ('rest_password', models.CharField(max_length=50)),
                ('rest_otp', models.IntegerField()),
                ('rest_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.Areamodel')),
                ('rest_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.RestautantType')),
            ],
        ),
    ]
