# Generated by Django 3.0.5 on 2020-04-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmodel',
            name='rest_statue',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
