# Generated by Django 3.0.5 on 2020-04-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurantmodel_rest_statue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantModel',
        ),
    ]
