# Generated by Django 3.0.5 on 2020-04-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurantmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantProduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('restro_name', models.CharField(max_length=60)),
                ('product_name', models.CharField(max_length=60, unique=True)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('product_discount', models.FloatField()),
                ('product_status', models.CharField(max_length=500)),
                ('Product_image', models.FileField(blank='True', null='True', upload_to='Restaurant/')),
            ],
        ),
    ]
