# Generated by Django 3.0.5 on 2020-05-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_restaurantproduct_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantproduct',
            name='product_result',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurantproduct',
            name='Product_image',
            field=models.FileField(blank='True', null='True', upload_to='Restro/'),
        ),
        migrations.AlterField(
            model_name='restaurantproduct',
            name='Product_img',
            field=models.ImageField(blank='True', default='Restaurant/food6.jpg', null='True', upload_to='Restaurant/'),
        ),
    ]
